In [1]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/transactions.csv")

In [2]:
df = pd.read_csv(data_path)
df

                           date    category  amount
0     2022-07-06 05:57:10 +0000  Restuarant    5.50
1     2022-07-06 05:57:27 +0000      Market    2.00
2     2022-07-06 05:58:12 +0000       Coffe   30.10
3     2022-07-06 05:58:25 +0000      Market   17.33
4     2022-07-06 05:59:00 +0000  Restuarant    5.50
...                         ...         ...     ...
3606  2024-09-29 04:53:24 +0000       Coffe   15.00
3607  2024-09-29 10:40:38 +0000  Restuarant    8.00
3608                 2025-03-01      travel   25.00
3609                 2025-03-10        Meal   50.00
3610                 2025-03-05        Rent  350.00

[3611 rows x 3 columns]

In [3]:
new_transaction = {
    "date": "2025-03-01",
    "category":"Food",
    "amount": 25.50
}

df = pd.concat([df, pd.DataFrame([new_transaction])], ignore_index=True)
df.to_csv(data_path, index=False)

df.tail()

                           date    category  amount
3607  2024-09-29 10:40:38 +0000  Restuarant     8.0
3608                 2025-03-01      travel    25.0
3609                 2025-03-10        Meal    50.0
3610                 2025-03-05        Rent   350.0
3611                 2025-03-01        Food    25.5

In [5]:
row_id = 0
df.loc[row_id, "amount"] = 40.00

df.to_csv(data_path, index=False)

df.head()

                        date    category  amount
0  2022-07-06 05:57:10 +0000  Restuarant   40.00
1  2022-07-06 05:57:27 +0000      Market    2.00
2  2022-07-06 05:58:12 +0000       Coffe   30.10
3  2022-07-06 05:58:25 +0000      Market   17.33
4  2022-07-06 05:59:00 +0000  Restuarant    5.50

In [6]:
row_id = 1

df = df.drop(row_id)
df = df.reset_index(drop=True)

df.to_csv(data_path, index=False)

df

                           date    category  amount
0     2022-07-06 05:57:10 +0000  Restuarant   40.00
1     2022-07-06 05:58:12 +0000       Coffe   30.10
2     2022-07-06 05:58:25 +0000      Market   17.33
3     2022-07-06 05:59:00 +0000  Restuarant    5.50
4     2022-07-06 05:59:15 +0000      Market   11.78
...                         ...         ...     ...
3606  2024-09-29 10:40:38 +0000  Restuarant    8.00
3607                 2025-03-01      travel   25.00
3608                 2025-03-10        Meal   50.00
3609                 2025-03-05        Rent  350.00
3610                 2025-03-01        Food   25.50

[3611 rows x 3 columns]