In [6]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/transactions.csv")

In [7]:
df = pd.read_csv(data_path)

# Add transaction_id if it does not exist
if "transaction_id" not in df.columns:
    df.insert(0, "transaction_id", range(1, len(df) + 1))

df

      transaction_id                       date    category  amount
0                  1  2022-07-06 05:57:10 +0000  Restuarant   40.00
1                  2  2022-07-06 05:58:12 +0000       Coffe   30.10
2                  3  2022-07-06 05:58:25 +0000      Market   17.33
3                  4  2022-07-06 05:59:00 +0000  Restuarant    5.50
4                  5  2022-07-06 05:59:15 +0000      Market   11.78
...              ...                        ...         ...     ...
3606            3607  2024-09-29 10:40:38 +0000  Restuarant    8.00
3607            3608                 2025-03-01      travel   25.00
3608            3609                 2025-03-10        Meal   50.00
3609            3610                 2025-03-05        Rent  350.00
3610            3611                 2025-03-01        Food   25.50

[3611 rows x 4 columns]

In [8]:
new_transaction = {
    "transaction_id": df["transaction_id"].max() + 1,
    "date": "2025-03-01",
    "category":"Food",
    "amount": 25.50
}

df = pd.concat([df, pd.DataFrame([new_transaction])], ignore_index=True)
df.to_csv(data_path, index=False)

df.tail()

      transaction_id        date category  amount
3607            3608  2025-03-01   travel    25.0
3608            3609  2025-03-10     Meal    50.0
3609            3610  2025-03-05     Rent   350.0
3610            3611  2025-03-01     Food    25.5
3611            3612  2025-03-01     Food    25.5

In [14]:
transaction_id = 1
new_amount = 45.00

if transaction_id in df["transaction_id"].values:
    df.loc[df["transaction_id"] == transaction_id, "amount"] = new_amount
else:
    print("Transaction ID not found")
df.loc[df["transaction_id"] == transaction_id, "amount"] = new_amount

df.to_csv(data_path, index=False)

df.head()

   transaction_id                       date    category  amount
0               1  2022-07-06 05:57:10 +0000  Restuarant   45.00
1               3  2022-07-06 05:58:25 +0000      Market   17.33
2               4  2022-07-06 05:59:00 +0000  Restuarant    5.50
3               5  2022-07-06 05:59:15 +0000      Market   11.78
4               6  2022-07-06 05:59:41 +0000  Restuarant   10.00

In [12]:
transaction_id = 2

df = df[df["transaction_id"] != transaction_id]

df = df.reset_index(drop=True)

df.to_csv(data_path, index=False)

df

      transaction_id                       date    category  amount
0                  1  2022-07-06 05:57:10 +0000  Restuarant   40.00
1                  3  2022-07-06 05:58:25 +0000      Market   17.33
2                  4  2022-07-06 05:59:00 +0000  Restuarant    5.50
3                  5  2022-07-06 05:59:15 +0000      Market   11.78
4                  6  2022-07-06 05:59:41 +0000  Restuarant   10.00
...              ...                        ...         ...     ...
3606            3608                 2025-03-01      travel   25.00
3607            3609                 2025-03-10        Meal   50.00
3608            3610                 2025-03-05        Rent  350.00
3609            3611                 2025-03-01        Food   25.50
3610            3612                 2025-03-01        Food   25.50

[3611 rows x 4 columns]