# Transaction Data Setup
This cell imports the required libraries and defines the path to the transaction dataset. 
Basic error handling ensures the file path is valid before loading the data later.

In [16]:
import pandas as pd
from pathlib import Path
from IPython.display import display

try:
    data_path = Path("../data/transactions.csv")
except FileNotFoundError:
    print("Error: The data file was not found. Please check the path.")
except KeyError as e:
    print(f"Missing column in dataset: {e}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")

# Load Dataset
This cell loads the CSV file into a pandas DataFrame and performs initial validation. 
If the dataset is empty or cannot be loaded, an error message is displayed.

In [17]:
try:
    df = pd.read_csv(data_path)
    if df.empty:
        print("No data available")    
    display(df)  # explicitly renders the DataFrame
except FileNotFoundError:
    print("Error: The data file was not found. Please check the path.")
except KeyError as e:
    print(f"Missing column in dataset: {e}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")

                           date    category  amount
0     2022-07-06 05:57:10 +0000  Restuarant   45.00
1     2022-07-06 05:58:25 +0000      Market   17.33
2     2022-07-06 05:59:00 +0000  Restuarant    5.50
3     2022-07-06 05:59:15 +0000      Market   11.78
4     2022-07-06 05:59:41 +0000  Restuarant   10.00
...                         ...         ...     ...
3608                   3/5/2025        Rent  350.00
3609                   3/1/2025        Food   25.50
3610                   3/1/2025        Food   25.50
3611                   3/1/2025        Food   25.50
3612                   3/1/2025        Food   25.50

[3613 rows x 3 columns]

# Add a New Transaction
This cell demonstrates how to append a new transaction to the dataset. 
Error handling ensures the DataFrame exists and that the required fields are valid before insertion.

In [19]:
try:
    new_transaction = {
        "date": "2025-03-01",
        "category":"Food",
        "amount": 25.50
    }
    
    df = pd.concat([df, pd.DataFrame([new_transaction])], ignore_index=True)
    df.to_csv(data_path, index=False)
    
    display(df.tail())
except FileNotFoundError:
    print("Error: The data file was not found. Please check the path.")
except KeyError as e:
    print(f"Missing column in dataset: {e}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")

            date category  amount
3610    3/1/2025     Food    25.5
3611    3/1/2025     Food    25.5
3612    3/1/2025     Food    25.5
3613  2025-03-01     Food    25.5
3614  2025-03-01     Food    25.5

# Update a Transaction
This cell updates the amount of an existing transaction. 
If the ID does not exist, the code safely handles the error and informs the user.

In [21]:
try:
    excel_row = 3612  # Excel row number (starts from 2, since row 1 is header)
    new_amount = 45.00
    df_index = excel_row - 2  # Convert to DataFrame index (0-based)
    
    if df_index in df.index:
        df.loc[df_index, "amount"] = new_amount
    else:
        print("Row number not found")
    
    df.to_csv(data_path, index=False)
    
    display(df)
except FileNotFoundError:
    print("Error: The data file was not found. Please check the path.")
except KeyError as e:
    print(f"Missing column in dataset: {e}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")

                           date    category  amount
0     2022-07-06 05:57:10 +0000  Restuarant   45.00
1     2022-07-06 05:58:25 +0000      Market   17.33
2     2022-07-06 05:59:00 +0000  Restuarant    5.50
3     2022-07-06 05:59:15 +0000      Market   11.78
4     2022-07-06 05:59:41 +0000  Restuarant   10.00
...                         ...         ...     ...
3610                   3/1/2025        Food   45.00
3611                   3/1/2025        Food   25.50
3612                   3/1/2025        Food   25.50
3613                 2025-03-01        Food   25.50
3614                 2025-03-01        Food   25.50

[3615 rows x 3 columns]

# Delete a Transaction
This cell removes a transaction, resets the index, 
and saves the updated dataset back to the CSV file with proper error handling.

In [22]:
try:
    excel_row = 3612  # Excel row number (starts from 2, since row 1 is header)
    df_index = excel_row - 2  # Convert to DataFrame index (0-based)
    
    if df_index in df.index:
        df = df.drop(index=df_index)
    else:
        print("Row number not found")
    
    df = df.reset_index(drop=True)
    
    df.to_csv(data_path, index=False)
    
    display(df)
except FileNotFoundError:
    print("Error: The data file was not found. Please check the path.")
except KeyError as e:
    print(f"Missing column in dataset: {e}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")

                           date    category  amount
0     2022-07-06 05:57:10 +0000  Restuarant   45.00
1     2022-07-06 05:58:25 +0000      Market   17.33
2     2022-07-06 05:59:00 +0000  Restuarant    5.50
3     2022-07-06 05:59:15 +0000      Market   11.78
4     2022-07-06 05:59:41 +0000  Restuarant   10.00
...                         ...         ...     ...
3609                   3/1/2025        Food   25.50
3610                   3/1/2025        Food   25.50
3611                   3/1/2025        Food   25.50
3612                 2025-03-01        Food   25.50
3613                 2025-03-01        Food   25.50

[3614 rows x 3 columns]